folders:
  - folder_path: "odin"
      description: "odin service folder"
jobs:
  - job_path: "odin/build_job"
      jenkinsfile_git_repo: "https://github.com/ecsworkshopee/odin.git"
      jenkinsfile_path: "Jenkinsfile"
      auto_trigger: true
